add_newline = true

format = """
[╭─](bold purple)\
[](purple)\
$username\
[](fg:purple bg:blue)\
$directory\
$git_branch\
$git_status\
[](blue)\
$line_break\
[╰─❯](bold purple) """

[username]
show_always = true
style_user = "fg:black bg:purple bold"
style_root = "fg:white bg:red bold"
format = "[ $user ]($style)"

[directory]
style = "fg:black bg:blue bold"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "fg:black bg:cyan bold"
format = "[](fg:blue bg:cyan)[ $symbol$branch ]($style)"

[git_status]
style = "fg:black bg:cyan bold"
format = "[$all_status$ahead_behind ]($style)"

[character]
disabled = true
