[MarkOS Appearance]
Name=Aurora
Wallpaper=markos-aurora.png
ColorScheme=prefer-dark
AccentColor=teal
IconTheme=MarkOS-Aurora
TerminalPalette=aurora
TerminalOpacity=0.92
StarshipPalette=aurora
FastfetchPalette=aurora
TerminalBackground=#071a1a
TerminalForeground=#ccfbf1
TerminalAccent=#2dd4bf
