[MarkOS Appearance]
Name=Cosmic
Wallpaper=markos-cosmic.png
ColorScheme=prefer-dark
AccentColor=purple
IconTheme=MarkOS-Cosmic
TerminalPalette=cosmic
TerminalOpacity=0.92
StarshipPalette=cosmic
FastfetchPalette=cosmic
TerminalBackground=#11111b
TerminalForeground=#cdd6f4
TerminalAccent=#cba6f7
