[MarkOS Appearance]
Name=Dawn
Wallpaper=markos-dawn.png
ColorScheme=default
AccentColor=orange
IconTheme=MarkOS-Dawn
TerminalPalette=dawn
TerminalOpacity=0.94
StarshipPalette=dawn
FastfetchPalette=dawn
TerminalBackground=#21150f
TerminalForeground=#ffedd5
TerminalAccent=#fb923c
